const facul = ("1,2,3,4,5,6,7,8")

// console.log(facul.charAt(4))
// console.log(facul.charCodeAt(0))
// console.log(facul.indexOf("C"))
// console.log(facul.substring(3))
// console.log(facul.substring(0,3))
// console.log("Faculdade ".concat(facul).concat(" Franca!!!"))
// console.log(facul.replace("F", 3))
console.log(facul.split(","))